//
// Created by Alan Freitas on 11/08/20.
//

#ifndef MATPLOTPLUSPLUS_FIGURE_FUNCTIONS_H
#define MATPLOTPLUSPLUS_FIGURE_FUNCTIONS_H

namespace matplot {}

#endif // MATPLOTPLUSPLUS_FIGURE_FUNCTIONS_H
